package deathOfThrones;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import deathOfThrones.Death;
import deathOfThrones.DeathRepository;

@Controller
@RequestMapping(path="/dot")
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private DeathRepository deathRepository;
	
	
	@GetMapping(path="/alldeath")
	public @ResponseBody Iterable<Death> getAllDeaths() {
		// This returns a JSON or XML with the users
		return deathRepository.findAll();
	}
	
	@GetMapping(path="/death")
	public @ResponseBody String getDeath(@RequestParam String name){
		return deathRepository.findByName(name).getMurder();
	}

	
	
}
